branch-defaults:
  main:
    environment: "Democici-env"
global:
  application_name: "application name"
  default_ec2_keyname: "Democici-env"
  default_platform: 64bit Amazon Linux 2/3.5.3
  default_region: ap-south-1
  sc: git